# Generated by Django 3.2 on 2023-11-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('cafeteria_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cafeteria_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServedTime',
            fields=[
                ('served_time_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('served_time_period', models.CharField(max_length=20)),
                ('cafeteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=20)),
                ('dish_price', models.IntegerField()),
                ('cafeteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.cafeteria')),
                ('served_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.servedtime')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comments_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.dish')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.User')),
            ],
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='campus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.campus'),
        ),
    ]
