# Generated by Django 3.2 on 2023-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20231119_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.FloatField(),
        ),
    ]
