# Generated by Django 3.2 on 2023-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20231119_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campus_name',
            field=models.CharField(max_length=100),
        ),
    ]
