# Generated by Django 3.2 on 2023-11-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_campus_campus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servedtime',
            name='cafeteria_id',
        ),
    ]
